name: Test

on: [push]

jobs:
  test:
  # где запускаем
  runs-on: ubuntu-latest
  # что делаем
  steps:
    # 1. Выкачиваем репозиторий
    - uses: actions/checkout@v3
    # 2. Настраиваем java
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    #Запуск тестов
    - run: ./gradlew clean test